------------------------------------------------------------------------------
-- PROJECT: ParIS
-- ENTITY : req_reg
------------------------------------------------------------------------------
-- DESCRIPTION: Register responsible to hold a request after the routing 
-- function schedules an output channel to be used by an incoming packet.
-- A registered request is hold until the packet trailer is delivered.
--
-- NOTE: Verificar se o custo de implementação pode ser reduzido utilizando-se
-- >>if generate<< na descricao do registrador
------------------------------------------------------------------------------
-- AUTHORS: Frederico G. M. do Espirito Santo 
--          Cesar Albenes Zeferino
-- CONTACT: zeferino@univali.br OR cesar.zeferino@gmail.com
------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.STD_LOGIC_1164.all;

-----------------
-----------------
ENTITY req_reg IS
-----------------
-----------------
  GENERIC (
    MODULE_ID    : STRING := "L";  -- identifier of the port in the router
    ROUTING_TYPE : STRING := "WF"  -- type of routing algorithm
  );
  PORT(
    -- System signals
    clk      : IN  STD_LOGIC;  -- clock
    rst      : IN  STD_LOGIC;  -- reset

    -- FIFO interface
    rok      : IN  STD_LOGIC;  -- FIFO has a data to be read (not empty)
    rd       : IN  STD_LOGIC;  -- command to read a data from the FIFO

    -- Framing bits
    bop      : IN  STD_LOGIC;  -- packet framing bit: begin of packet
    eop      : IN  STD_LOGIC;  -- packet framing bit: end   of packet

    -- Requests
    in_reqL  : IN  STD_LOGIC;  -- request to Lout (input)
    in_reqN  : IN  STD_LOGIC;  -- request to Nout (input)
    in_reqE  : IN  STD_LOGIC;  -- request to Eout (input)
    in_reqS  : IN  STD_LOGIC;  -- request to Sout (input)
    in_reqW  : IN  STD_LOGIC;  -- request to Wout (input)
    out_reqL : OUT STD_LOGIC;  -- request to Lout (output)
    out_reqN : OUT STD_LOGIC;  -- request to Nout (output)
    out_reqE : OUT STD_LOGIC;  -- request to Eout (output)
    out_reqS : OUT STD_LOGIC;  -- request to Sout (output)
    out_reqW : OUT STD_LOGIC   -- request to Wout (output)
  );
END req_reg;
  
---------------------------------
---------------------------------
ARCHITECTURE arch_1 OF req_reg IS
---------------------------------
---------------------------------
SIGNAL reqL       : STD_LOGIC;  -- request to Lout
SIGNAL reqN       : STD_LOGIC;  -- request to Nout
SIGNAL reqE       : STD_LOGIC;  -- request to Eout
SIGNAL reqS       : STD_LOGIC;  -- request to Sout
SIGNAL reqW       : STD_LOGIC;  -- request to Wout
SIGNAL requesting : STD_LOGIC;  -- there exists someone requesting

BEGIN
  -- Determines if there existis someone requesting
  requesting <= reqL OR reqN OR reqE OR reqS OR reqW;

  -- The following process implements a register which determines 
  -- the state of the requests to the output channels. It takes 
  -- into account the type of routing function (eg. routing_xy),
  -- the signals generated by the routing function, and the 
  -- module ID (that is: L, N, and so on).
  --------------------------------------
  PROCESS(clk,rst,rok,rd,eop,requesting)
  --------------------------------------
  BEGIN
 
    IF (rst='1')THEN
      reqL <= '0';
      reqN <= '0';
      reqE <= '0';
      reqS <= '0';
      reqW <= '0';

    ELSIF (clk'EVENT and clk='1') THEN

      -- If there is no registered request and a header is present, 
      -- it registers the new request determined by the routing function
      ------------------------------------------------------
      IF ((rok='1') AND (bop='1') AND (requesting='0')) THEN
      ------------------------------------------------------
        -- reqL: not registered by module L 
        ----------
        request_L:
        ----------
          IF (MODULE_ID = "L") THEN
            reqL <= '0';
          ELSE
            reqL <= in_reqL;
          END IF; 

        -- reqN: not registered by module N 
        ----------
        request_N:
        ----------
          IF (MODULE_ID = "N") THEN
            reqN <= '0';
          ELSE
            reqN <= in_reqN;
          END IF; 

        -- reqE: not registered by module E, and, in the case of
        -- routing XY, by modules N and S  
        ----------
        request_E:
        ----------
           IF (MODULE_ID = "E") THEN
            reqE <= '0';
           ELSE
             IF (ROUTING_TYPE="XY") THEN
              IF ((MODULE_ID="N") OR (MODULE_ID="S")) THEN
                reqE <= '0';        
              ELSE        
                reqE <= in_reqE;
              END IF;
             ELSE
                reqE <= in_reqE;      
             END IF;    
          END IF;

        -- reqS: not registered by module S     
        ----------
        request_S:
        ----------
          IF (MODULE_ID = "S") THEN
            reqS <= '0';
          ELSE
            reqS <= in_reqS;
          END IF; 

        -- reqW: not registered by module W, and, in the case of
        -- routing XY or WF, by modules N and S  
        ----------
        request_W:
        ----------
           IF (MODULE_ID = "W") THEN
            reqW <= '0';
           ELSE  
             IF ((ROUTING_TYPE="XY") OR (ROUTING_TYPE="WF")) THEN
              IF ((MODULE_ID="N") OR (MODULE_ID="S")) THEN
                reqW <= '0'; 
              ELSE 
                reqW <= in_reqW;
              END IF; 
             ELSE
                reqW <= in_reqW; 
             END IF; 
          END IF;
        
      -- If a trailer is present and it is being read by the receiver, 
      -- it resets the registered request
      --------------------------------------------------
      ELSIF  ((rok='1') AND (eop='1') AND (rd='1')) THEN
      --------------------------------------------------
        reqL <= '0';
        reqN <= '0';
        reqE <= '0';
        reqS <= '0';
        reqW <= '0';
      END IF;
    END IF;
  END PROCESS;

  ----------
  -- Outputs
  ----------
  out_reqL <= reqL;
  out_reqN <= reqN;
  out_reqE <= reqE;
  out_reqS <= reqS;
  out_reqW <= reqW;

END arch_1;
